services:
  db:
    image: postgres:16
    container_name: menuart_db
    environment:
      POSTGRES_USER: menuart
      POSTGRES_PASSWORD: menuartpass
      POSTGRES_DB: menuart
    ports:
      - "5432:5432"
    volumes:
      - menuart_pg:/var/lib/postgresql/data

volumes:
  menuart_pg:
